Repository intel/workload-collocation-agent, pull requests merged in 2018-12, with the labels that each got.

#8 Introduce support for workloads versions and workloads components count.
  owca/wrapper/parser_mutilate.py
  tests/wrapper/test_parser_mutilate.py
  workloads/README.rst
  workloads/cassandra_stress/cassandra_stress.aurora
  workloads/common.aurora
  workloads/filter_plugins/workload_job_iterator.py
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
  workloads/specjbb/specjbb.aurora
  workloads/tensorflow_benchmark/tensorflow-benchmark-prediction.aurora
  workloads/tensorflow_benchmark/tensorflow-benchmark-training.aurora
Labels: ready for review

#14 Fix in run_workloads.yaml: add needed vars for clean_jobs.
  workloads/run_workloads.yaml
Labels: trivial

#15 Add new variable to workloads/common.aurora application_version_name …
  workloads/README.rst
  workloads/common.aurora
Labels: ready for review

#17 Update parser_ycsb.py to handle ops-per-second properly
  owca/wrapper/parser_ycsb.py
Labels: ready for review, trivial

#18 Fix header and warning for workload docs
  workloads/README.rst
  workloads/tensorflow_train/README.rst
Labels: trivial

#19 Enable and fix flakes for workloads python code
  tox.ini
  workloads/filter_plugins/workload_job_iterator.py
  workloads/tensorflow_inference/load_nn_weights.py
  workloads/tensorflow_inference/prep_dataset_fruits.py
Labels: trivial

#20 Cassandra stress duration option
  workloads/cassandra_stress/cassandra_stress.aurora
Labels: trivial

#21 Add abstract classes and interfaces for allocation functionality.
  owca/allocators.py
Labels: ready for review
