Repository intel/workload-collocation-agent, pull requests merged in 2019-11, with the labels that each got.

#300 Fix inconsistency between unfified "mems" TaskResource in Mesos and Kubernetes
  docs/detection.rst
  docs/kubernetes.rst
  docs/mesos.rst
  tests/test_kubernetes.py
  tests/test_mesos.py
  tests/test_resources.py
  wca/kubernetes.py
  wca/mesos.py
  wca/nodes.py
  wca/resources.py
Labels: bug, ready for review

#307 Fix build cgroup path for systemd in Kubernetes
  tests/e2e/demo_scenarios/common/wca_config_mesos.yaml
  tests/test_kubernetes.py
  wca/kubernetes.py
Labels: ready for review

#303 Avoid redundant init variables in runners objects.
  README.rst
  configs/extra/numa_allocator_mesos.yaml
  configs/extra/numa_allocator_static.yaml
  configs/extra/static_aep.yaml
  configs/extra/static_allocator.yaml
  configs/kubernetes/kubernetes_aep_36.yaml
  configs/kubernetes/kubernetes_aep_37.yaml
  configs/kubernetes/kubernetes_aep_38.yaml
  configs/kubernetes/kubernetes_aep_39.yaml
  configs/kubernetes/kubernetes_aep_40.yaml
  configs/kubernetes/kubernetes_example_allocator.yaml
  configs/mesos/mesos_example_allocator.yaml
  configs/mesos/mesos_external_detector.yaml
  docs/allocation.rst
  docs/detection.rst
  docs/extending.rst
  docs/external_detector_example.rst
  docs/install.rst
  docs/prometheus.rst
  docs/ssl.rst
  tests/e2e/demo_scenarios/common/wca_config_kubernetes.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes_daemonset.yaml
  tests/e2e/demo_scenarios/common/wca_config_mesos.yaml
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_allocation_helpers.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/tester/configs/tester_example.yaml
  wca/components.py
  wca/runners/allocation.py
  wca/runners/detection.py
  wca/runners/measurement.py
Labels: ready for review

#306 Revert deleted mutilate workload
  Jenkinsfile
  Makefile
  examples/kubernetes/README.md
  examples/workloads/memtier_benchmark/Dockerfile
  examples/workloads/mutilate/Dockerfile
  examples/workloads/mutilate/mutilate.aurora
  examples/workloads/mutilate/mutilate.py
  examples/workloads/run_workloads.yaml
  examples/workloads/run_workloads_inventory.template.yaml
  examples/workloads/wrapper/wrapper/parser_memtier.py
  examples/workloads/wrapper/wrapper/parser_mutilate.py
  tests/e2e/demo_scenarios/run_workloads/inventory.yaml
  tests/e2e/test_wca_metrics.py
  tests/wrapper/test_parser_mutilate.py
Labels: ready for review

#313 Fix build cgroup path for systemd in Kubernetes (#307)
  tests/e2e/demo_scenarios/common/wca_config_mesos.yaml
  tests/test_kubernetes.py
  wca/kubernetes.py
Labels: ready for review

#312 Sysbench dockerfile
  examples/workloads/sysbench/Dockerfile
Labels: ready for review

#315 Deleted kubernetes/monitoring/_archives
  examples/kubernetes/monitoring/_archives/prometheus/README.md
  examples/kubernetes/monitoring/_archives/prometheus/prometheus-apms.rules.yaml
  examples/kubernetes/monitoring/_archives/prometheus/prometheus.rules.yaml
  examples/kubernetes/monitoring/_archives/prometheus/prometheus.yaml
Labels: ready for review

#316 Handle cgroup file existence race during task discovery for Mesos
  wca/mesos.py
Labels: ready for review

#311 Simplify API for plugins
  docs/allocation.rst
  docs/detection.rst
  docs/external_detector_example.rst
  docs/prometheus.rst
  docs/ssl.rst
  tests/extra/test_static_allocator.py
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_allocation_helpers.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/test_anomalies.py
  tests/tester/tester.py
  tests/testing.py
  wca/allocators.py
  wca/components.py
  wca/detectors.py
  wca/extra/aep_detector.py
  wca/extra/numa_allocator.py
  wca/extra/static_allocator.py
  wca/mesos.py
  wca/nodes.py
  wca/resources.py
  wca/runners/allocation.py
  wca/runners/detection.py
  wca/runners/measurement.py
Labels: ready for review

#321 Marta's perf uncore hierarchical support.
  configs/extra/numa_allocator_k8s.yaml
  tests/e2e/test_wca_metrics.py
  tests/test_metrics.py
  tests/test_perf.py
  tests/test_perf_uncore.py
  wca/kubernetes.py
  wca/main.py
  wca/metrics.py
  wca/perf.py
  wca/perf_uncore.py
  wca/platforms.py
  wca/storage.py
Labels: ready for review

#324 UPI metrics cont. of Marta's work
  configs/extra/numa_allocator_k8s.yaml
  tests/test_perf.py
  wca/metrics.py
  wca/perf.py
  wca/perf_uncore.py
  wca/runners/measurement.py
Labels: ready for review

#327 Fix loggers configuration precedance (from command line and config file)
  wca/main.py
Labels: ready for review, trivial

#325 Check if swap is disabled before using migrate_pages allocation.
  tests/test_cgroups_allocations.py
  tests/test_platforms.py
  tests/testing.py
  wca/cgroups_allocations.py
  wca/platforms.py
Labels: ready for review
