Repository intel/workload-collocation-agent, pull requests merged in 2019-05, with the labels that each got.

#120 Fix build images conditional
  Jenkinsfile
Labels: bug, trivial

#122 Fix static allocations rules merging
  owca/extra/static_allocator.py
Labels: bug, ready for review, trivial

#125 Fix RDT cache and MBM monitoring is discovered
  wca/platforms.py
Labels: bug, ready for review

#126 Another RDT discovery fix and unit tests
  tests/test_platforms.py
  wca/platforms.py
Labels: ready for review, trivial

#127 RDT discovery fix part3 (MBM discovery)
  tests/test_platforms.py
  wca/platforms.py
Labels: ready for review, trivial

#130 Allow to provide default labels and resources for StaticNode
  tests/extra/test_static_node.py
  wca/extra/static_node.py
Labels: ready for review, trivial

#131 Database abstraction fix
  tests/test_databases.py
  wca/databases.py
Labels: ready for review

#135 Fix wrong address to build status icon.
  README.rst
Labels: trivial

#137 Better logging
  wca/cgroups.py
  wca/containers.py
  wca/resctrl.py
  wca/storage.py
Labels: ready for review

#139 Handle FileNotFound
  wca/cgroups.py
Labels: ready for review, trivial

#140 MBA allocations validate fix
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_allocation_helpers.py
  wca/resctrl_allocations.py
  wca/runners/allocation.py
  wca/testing.py
Labels: ready for review

#144 Add cpu_model field to Platform class.
  docs/detection.rst
  tests/test_platforms.py
  wca/platforms.py
Labels: ready for review

#138 Update task definition
  tests/runners/test_runners_allocation.py
  tests/test_containers.py
  wca/containers.py
  wca/extra/static_allocator.py
  wca/runners/allocation.py
Labels: request for comments

#146 Workload_instance in wrapper_labels
  workloads/common.py
Labels: ready for review, trivial

#141 Implement cpuset allocation
  configs/extra/tester_config.yaml
  tests/runners/test_runners_measurement.py
  tests/test_cgroups.py
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  wca/allocators.py
  wca/cgroups.py
  wca/cgroups_allocations.py
  wca/containers.py
  wca/extra/tester.py
  wca/runners/allocation.py
  wca/runners/measurement.py
  wca/testing.py
Labels: ready for review

#143 Validate input from plugins allocator and detector.
  tests/config/test_validate_values.py
  wca/config.py
  wca/main.py
  wca/runners/allocation.py
  wca/runners/detection.py
Labels: ready for review

#142 Check that full path is used for location of config file
  Jenkinsfile
  README.rst
  docs/external_detector_example.rst
  tests/test_main.py
  wca/main.py
Labels: ready for review

#147 Readme fixes
  README.rst
  docs/context.png
Labels: ready for review
