Repository intel/workload-collocation-agent, pull requests merged in 2019-10, with the labels that each got.

#273 Rpc-perf dockerfile rust version fix
  workloads/rpc_perf/Dockerfile
Labels: ready for review

#271 Kubernetes e2e tests migration
  Dockerfile
  Jenkinsfile
  tests/e2e/demo_scenarios/common/inventory-kubernetes.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes.yaml
  workloads/rpc_perf/Dockerfile
Labels: ready for review

#274 Merge 1.0.x into master
  Jenkinsfile
  Pipfile
  Pipfile.lock
  workloads/filter_plugins/workload_job_iterator.py
Labels: ready for review

#267 Add "memory_bandwidth_local"/"memory_bandwidth_remote" metrics and cpu based perf metrics.
  tests/fixtures/procinfo_1socket_4cores_8cpus.txt
  tests/fixtures/procinfo_2sockets_ht.txt
  tests/fixtures/procinfo_2sockets_noht.txt
  tests/resctrl/test_resctrl_measurements.py
  tests/runners/test_runners_allocation_helpers.py
  tests/runners/test_runners_measurement.py
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  tests/test_perf.py
  tests/test_platforms.py
  tests/tester/configs/tester_config.yaml
  tests/tester/configs/tester_example.yaml
  tests/testing.py
  wca/containers.py
  wca/metrics.py
  wca/perf.py
  wca/perf_const.py
  wca/platforms.py
  wca/resctrl.py
  wca/runners/allocation.py
  wca/runners/detection.py
  wca/runners/measurement.py
Labels: work in progress

#276 Add latest 'urllib3' module.
  Pipfile
  Pipfile.lock
Labels: ready for review, trivial

#277 Fix `PEX_INHERIT_PATH` flag for integration tests.
  Jenkinsfile
  docs/extending.rst
Labels: ready for review

#279 Handle missing container race for perf/cgroup based metrics.
  wca/perf.py
Labels: ready for review

#283 Remove urllib3 from Pipfile.
  Pipfile
  Pipfile.lock
Labels: ready for review

#286 Adding chierarchical measurements
  tests/test_cgroups.py
  tests/test_platforms.py
  tests/testing.py
  wca/cgroups.py
  wca/extra/numa_allocator.py
  wca/metrics.py
  wca/platforms.py
  wca/runners/measurement.py
Labels: work in progress

#282 Pref pmu devel
  setup.py
  tests/runners/test_runners_measurement.py
  tests/test_perf.py
  tests/test_perf_pmu.py
  wca/components.py
  wca/containers.py
  wca/metrics.py
  wca/perf_pmu.py
  wca/runners/allocation.py
  wca/runners/detection.py
  wca/runners/measurement.py
Labels: ready for review

#291 Perf uncore
  tests/test_perf_uncore.py
  wca/components.py
  wca/perf.py
  wca/perf_uncore.py
  wca/runners/allocation.py
  wca/runners/detection.py
  wca/runners/measurement.py
Labels: ready for review
