Repository intel/workload-collocation-agent, pull requests merged in 2019-12, with the labels that each got.

#332 Measurement API documentation.
  README.rst
  docs/README.rst
  docs/measurement.rst
  wca/runners/measurement.py
Labels: ready for review

#328 Metrics cleanup, rename and description
  configs/extra/numa_allocator_k8s.yaml
  docs/metrics.csv
  docs/metrics.rst
  docs/metrics_sources.rst
  tests/e2e/test_wca_metrics.py
  tests/fixtures/proc-vmstat.txt
  tests/resctrl/test_resctrl_measurements.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/test_cgroups.py
  tests/test_cgroups_allocations.py
  tests/test_mesos.py
  tests/test_metrics.py
  tests/test_perf.py
  tests/test_perf_uncore.py
  tests/test_platforms.py
  tests/test_wss.py
  tests/tester/configs/tester_config.yaml
  tests/tester/configs/tester_example.yaml
  tests/tester/tester.py
  tests/testing.py
  util/docs.py
  wca/allocators.py
  wca/cgroups.py
  wca/cgroups_allocations.py
  wca/extra/numa_allocator.py
  wca/kubernetes.py
  wca/main.py
  wca/metrics.py
  wca/perf.py
  wca/perf_const.py
  wca/perf_uncore.py
  wca/platforms.py
  wca/profiling.py
  wca/resctrl.py
  wca/resources.py
  wca/runners/allocation.py
  wca/runners/measurement.py
  wca/storage.py
  wca/wss.py
Labels: ready for review

#296 Getting rid of null pointer dereference
  wca/runners/allocation.py
Labels: bug, security

#269 Avoid Log Forging
  tests/test_main.py
  wca/main.py
Labels: security

#335 Allocation API update (memory_migrate and other refer to new measurements.rst)
  docs/allocation.rst
Labels: request for comments

#337 API generator
  Jenkinsfile
  README.rst
  docs/README.rst
  docs/api.rst
  util/docs.py
  wca/components.py
  wca/extra/static_node.py
  wca/runners/allocation.py
  wca/runners/detection.py
  wca/runners/measurement.py
  wca/storage.py
Labels: ready for review

#334 Fix e2e tests and removed unused and out of date files.
  Jenkinsfile
  examples/kubernetes/monitoring/grafana/dashboards/2LM APM latency.json
  examples/kubernetes/monitoring/grafana/dashboards/2LM APM throughout.json
  examples/kubernetes/monitoring/grafana/dashboards/2LM bandwidth degradation.json
  examples/kubernetes/monitoring/grafana/dashboards/2LM contention demo.json
  examples/kubernetes/monitoring/prometheus/prometheus_rule.wca.yaml
  examples/kubernetes/monitoring/wca/wca-config.yaml
  examples/kubernetes/scheduler/README.md
  examples/kubernetes/scheduler/k8s_extender.py
  examples/kubernetes/scheduler/kube-scheduler.yaml
  examples/kubernetes/scheduler/scheduler-policy.json
  wca/metrics.py
  wca/perf_const.py
Labels: work in progress

#338 master with 1.0.x 12 4 2019
  Dockerfile
  README.rst
  tests/test_main.py
  wca/main.py
Labels: work in progress

#340 E2E fixes and debugging
  Jenkinsfile
  Makefile
  README.rst
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  docs/metrics_sources.rst
  examples/kubernetes/monitoring/prometheus/prometheus_rule.wca.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes_daemonset.yaml
  tests/e2e/demo_scenarios/common/wca_config_mesos.yaml
  tests/e2e/demo_scenarios/run_workloads/inventory.yaml
  tests/e2e/test_wca_metrics.py
  tests/runners/test_runners_measurement.py
  tests/test_kubernetes.py
  tests/testing.py
  tests/wrapper/test_parser.py
  tests/wrapper/test_parser_cassandra_stress.py
  tests/wrapper/test_parser_mutilate.py
  tests/wrapper/test_parser_rpc_perf.py
  tests/wrapper/test_parser_specjbb.py
  tests/wrapper/test_parser_stress_ng.py
  tests/wrapper/test_parser_ycsb.py
  wca/cgroups_allocations.py
  wca/containers.py
  wca/metrics.py
  wca/runners/allocation.py
  wca/runners/measurement.py
  wca/storage.py
Labels: work in progress

#342 Replace MeasurmentRunner action_dealy with interval
  configs/extra/numa_allocator_k8s.yaml
  configs/extra/numa_allocator_mesos.yaml
  configs/extra/numa_allocator_static.yaml
  configs/kubernetes/kubernetes_example_allocator.yaml
  configs/kubernetes/kubernetes_incluster_measurements.yaml
  configs/mesos/mesos_example_allocator.yaml
  configs/mesos/mesos_external_detector.yaml
  docs/api.rst
  docs/install.rst
  docs/measurement.rst
  examples/kubernetes/monitoring/wca/wca-config.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes_daemonset.yaml
  tests/e2e/demo_scenarios/common/wca_config_mesos.yaml
  tests/runners/test_runners_allocation_helpers.py
  tests/tester/configs/tester_example.yaml
  wca/runners/measurement.py
Labels: ready for review

#343 Remove unnecessary files and clean example configs
  Jenkinsfile
  configs/extra/numa_allocator_k8s.yaml
  configs/extra/numa_allocator_mesos.yaml
  configs/extra/numa_allocator_static.yaml
  configs/extra/static_measurements_with_extra_metrics.yaml
  tests/e2e/demo_scenarios/common/inventory-kubernetes-daemonset.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes_daemonset.yaml
Labels: trivial

#344 Add format standard for docstrings
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  util/docs.py
  wca/allocators.py
  wca/components.py
  wca/detectors.py
  wca/extra/numa_allocator.py
  wca/extra/static_allocator.py
  wca/extra/static_node.py
  wca/kubernetes.py
  wca/mesos.py
  wca/metrics.py
  wca/runners/allocation.py
  wca/runners/detection.py
  wca/runners/measurement.py
  wca/security.py
  wca/storage.py
Labels: ready for review

#345 Handle cgroups cpuset allocation for deeper hierarchy.
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  wca/cgroups_allocations.py
  wca/containers.py
Labels: work in progress

#348 Fix improper loggers configuration precedence.
  docs/logging.rst
  wca/main.py
Labels: ready for review

#351 Fix for numa related metric(str instead of int)
  tests/extra/test_numa_allocator.py
  tests/test_cgroups.py
  util/docs.py
  wca/cgroups.py
  wca/extra/numa_allocator.py
Labels: ready for review

#349 Fix improper loggers configuration precedence for 1.0.x
  docs/logging.rst
  wca/main.py
Labels: ready for review

#355 Update metrics docs and new CPU number label
  README.rst
  docs/README.rst
  docs/metrics.rst
  tests/test_platforms.py
  wca/platforms.py
  wca/runners/measurement.py
Labels: ready for review

#352 Fixing workloads for e2e
  Jenkinsfile
  examples/kubernetes/workloads/memcached-mutilate/base/mutilate.yaml
  tests/e2e/demo_scenarios/run_workloads/inventory.yaml
  tests/e2e/test_wca_metrics.py
Labels: ready for review

#357 Update dependencies to latest available versions.
  Makefile
  Pipfile
  Pipfile.lock
Labels: work in progress

#358 Missing perf based metrics description and new metrics.
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  docs/metrics_sources.rst
  util/docs.py
  wca/metrics.py
  wca/perf_const.py
Labels: ready for review

#362 Update documentation - centos 7.6 as requirement and build pex in doc…
  README.rst
  configs/extra/static_allocator.yaml
  docs/allocation.rst
  docs/development.rst
  docs/install.rst
  docs/kafka_storage.rst
  docs/measurement.rst
Labels: ready for review

#359 Readme improvements
  examples/kubernetes/monitoring/README.md
  examples/kubernetes/monitoring/fluentd/README.md
  examples/kubernetes/monitoring/wca/README.md
Labels: ready for review

#363 Migrate pages fixes
  tests/test_cgroups_allocations.py
  wca/cgroups_allocations.py
Labels: ready for review

#360 Tag images create by WCA with branch name and check that there is enough available PMU counters.
  Jenkinsfile
  tests/test_perf.py
  wca/perf.py
  wca/runners/measurement.py
Labels: ready for review

#365 Division by zero fix
  wca/perf.py
Labels: trivial

#361 Remove unstable workloads from e2e 1.0.x
  Jenkinsfile
  tests/e2e/test_wca_metrics.py
Labels: ready for review

#366 Derived metric for perf cgroup now work with dynamic hierarchy workaround
  docs/metrics.csv
  docs/metrics.rst
  docs/metrics_sources.rst
  tests/test_perf.py
  wca/metrics.py
  wca/perf.py
  wca/runners/measurement.py
Labels: ready for review

#368 Metrics better description
  docs/metrics_sources.rst
  wca/metrics.py
Labels: trivial

#369 Tag WCA with branch name and restore fail fast.
  Jenkinsfile
Labels: trivial

#370 Check if docs were regenerated
  Jenkinsfile
  docs/metrics.csv
  docs/metrics.rst
Labels: ready for review

#371 Update examples documentation (kubernetes manifests and docs)
  Dockerfile
  docs/kubernetes.rst
  examples/README.rst
  examples/kubernetes/README.md
  examples/kubernetes/README.rst
  examples/kubernetes/monitoring/wca/README.md
  examples/kubernetes/monitoring/wca/kustomization.yaml
  examples/workloads/README.rst
Labels: ready for review

#372 Disable default labels generators (not used for Kubernetes)
  tests/runners/test_runners_measurement.py
  wca/runners/measurement.py
Labels: ready for review, trivial
