Repository intel/workload-collocation-agent, pull requests merged in 2019-04, with the labels that each got.

#78 Allocation[7]: Allocation runner.
  owca/allocators.py
  owca/components.py
  owca/containers.py
  owca/main.py
  owca/metrics.py
  owca/resctrl_allocations.py
  owca/runners/allocation.py
  owca/testing.py
  tests/resctrl/test_resctrl_allocations.py
  tests/resctrl/test_resctrl_helpers.py
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_allocation_helpers.py
Labels: ready for review

#80 Perf module improvements
  owca/perf.py
  tests/test_perf.py
Labels: trivial

#86 Allocation[7] - final docs and examples
  README.rst
  configs/extra/static_allocator.yaml
  configs/extra/static_allocator_config.yaml
  configs/extra/static_measurements.yaml
  configs/extra/tester_example.yaml
  configs/mesos/mesos_external_detector.yaml
  configs/mesos_external_detector.yaml
  configs/mesos_kafka_example.yaml
  configs/systemd-unit/owca.service
  docs/allocation.rst
  docs/detection.rst
  docs/development.rst
  docs/mesos.rst
  example/external_package.py
  owca/allocators.py
  owca/components.py
  owca/config.py
  owca/extra/__init__.py
  owca/extra/static_allocator.py
  owca/extra/static_node.py
  owca/main.py
  owca/metrics.py
  owca/perf.py
  owca/resctrl.py
  owca/runners/allocation.py
  owca/runners/detection.py
  owca/runners/measurement.py
  owca/storage.py
  tests/extra/test_static_allocator.py
  tests/extra/test_static_node.py
  tests/runners/test_runners_allocation.py
Labels: ready for review

#87 Static allocator better logs and fix mb control initialization.
  docs/allocation.rst
  owca/extra/static_allocator.py
  owca/resctrl.py
  owca/resctrl_allocations.py
  owca/runners/allocation.py
  owca/runners/detection.py
  owca/runners/measurement.py
  owca/testing.py
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_allocation_helpers.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
Labels: ready for review

#84 Kubernetes support.
  README.rst
  configs/extra/static_allocator_config.yaml
  configs/extra/tester_example.yaml
  configs/kubernetes/kubernetes_example_allocator.yaml
  docs/detection.rst
  docs/kubernetes.rst
  owca/cgroups.py
  owca/cgroups_allocations.py
  owca/components.py
  owca/containers.py
  owca/extra/static_node.py
  owca/kubernetes.py
  owca/mesos.py
  owca/metrics.py
  owca/nodes.py
  owca/perf.py
  owca/resctrl_allocations.py
  owca/runners/allocation.py
  owca/testing.py
  tests/extra/test_static_node.py
  tests/fixtures/kubernetes_get_state.json
  tests/fixtures/kubernetes_get_state_not_ready.json
  tests/resctrl/test_resctrl_allocations.py
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_allocation_helpers.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  tests/test_kubernetes.py
  tests/test_mesos.py
  tests/test_metrics.py
Labels: ready for review

#90 Don't accept unknown fields in config file
  owca/main.py
  tests/test_main.py
Labels: ready for review

#91 Improve mesos doc.
  docs/mesos.rst
Labels: ready for review

#62 Kubernetes[run_workloads]: adapt run_workloads to support kubernetes.
  tox.ini
  workloads/cassandra/cassandra.py
  workloads/cassandra_stress/cassandra_stress.py
  workloads/common.py
  workloads/mutilate/mutilate.py
  workloads/redis/redis.py
  workloads/rpc_perf/rpc_perf.py
  workloads/run_workloads.yaml
  workloads/specjbb/specjbb.py
  workloads/stress_ng/stress_ng.py
  workloads/twemcache/twemcache.py
  workloads/ycsb/ycsb.py
Labels: work in progress

#97 Fix in run_workloads template file.
  workloads/run_workloads_inventory.template.yaml
Labels: ready for review

#98 Allow run pex file in debug mode.
  docs/development.rst
  owca/main.py
  owca/resctrl.py
Labels: trivial

#100 LogStorage with overwrite mode to be used together with KafkaStorage
  owca/storage.py
  tests/storage/test_log_storage.py
Labels: trivial

#99 Check rdt access only when needed (rdt is enabled)
  owca/runners/measurement.py
  owca/security.py
  tests/test_security.py
Labels: trivial

#101 Add debug mode for wrappers.
  owca/wrapper/wrapper_main.py
Labels: ready for review

#103 Better test results
  .gitignore
  Jenkinsfile
  Makefile
Labels: ready for review, trivial

#102 Optional timestamp for LogStorage to enabled NodeEporter
  owca/storage.py
  tests/storage/test_log_storage.py
  tests/storage/test_storage.py
Labels: ready for review, trivial

#96 Config validation
  docs/allocation.rst
  owca/allocators.py
  owca/config.py
  owca/extra/static_allocator.py
  owca/extra/static_node.py
  owca/kubernetes.py
  owca/mesos.py
  owca/runners/allocation.py
  owca/runners/detection.py
  owca/runners/measurement.py
  owca/storage.py
  tests/config/test_dataclasses.py
  tests/config/test_validate_values.py
Labels: ready for review

#95 Configurable perf events (support for raw and predefined dervied events)
  configs/extra/static_measurements_with_extra_metrics.yaml
  docs/allocation.rst
  owca/containers.py
  owca/extra/static_node.py
  owca/metrics.py
  owca/perf.py
  owca/perf_const.py
  owca/runners/allocation.py
  owca/runners/detection.py
  owca/runners/measurement.py
  owca/testing.py
  tests/extra/test_static_node.py
  tests/test_containers.py
  tests/test_perf.py
Labels: ready for review

#105 Add tensorflow_benchmark; add support for namespaces; other minor improvements.
  workloads/common.py
  workloads/redis/redis.py
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
  workloads/tensorflow_benchmark/Dockerfile
  workloads/tensorflow_benchmark/tensorflow-benchmark-prediction.py
  workloads/tensorflow_benchmark/tensorflow-benchmark-training.py
Labels: ready for review

#107 Fix mb schemata write for RDT.
  owca/resctrl_allocations.py
  owca/runners/allocation.py
  tests/resctrl/test_resctrl_allocations.py
Labels: ready for review

#108 Prometheus docs
  .gitignore
  configs/extra/static_measurements_for_node_exporter.yaml
  docs/README.rst
  docs/prometheus.rst
Labels: trivial

#110 Fix minor bug for tensorflow benchmark training.
  workloads/tensorflow_benchmark/tensorflow-benchmark-training.py
Labels: ready for review

#109 Remove workloads: workloads/tensorflow_train and workloads/tensorflow…
  Jenkinsfile
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
  workloads/tensorflow_inference/Dockerfile
  workloads/tensorflow_inference/README.rst
  workloads/tensorflow_inference/inference
  workloads/tensorflow_inference/load_nn_weights.py
  workloads/tensorflow_inference/prep_dataset_fruits.py
  workloads/tensorflow_inference/requirements.txt
  workloads/tensorflow_inference/tensorflow_inference.aurora
  workloads/tensorflow_train/Dockerfile
  workloads/tensorflow_train/README.rst
  workloads/tensorflow_train/prep_dataset.py
  workloads/tensorflow_train/requirements.txt
  workloads/tensorflow_train/tensorflow_train.aurora
  workloads/tensorflow_train/training
Labels: ready for review

#112 Fixed passing arguments to commands in workloads.
  workloads/cassandra_stress/cassandra_stress.py
  workloads/mutilate/mutilate.py
Labels: ready for review

#111 Upgrade urllib3
  Pipfile
  Pipfile.lock
Labels: security

#89 Add integration tests "Tester" component.
  Jenkinsfile
  configs/extra/tester_config.yaml
  configs/extra/tester_example.yaml
  owca/extra/static_allocator.py
  owca/extra/tester.py
  owca/testing.py
  tests/extra/test_static_allocator.py
  tests/extra/test_tester.py
  tests/extra/tester_config.yaml
Labels: ready for review

#113 Fix bug multiple pods with the same name on different nodes.
  workloads/common.py
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
Labels: ready for review

#92 Database abstraction for etcd/zookeeper.
  Pipfile
  Pipfile.lock
  owca/databases.py
  tests/test_databases.py
Labels: ready for review, request for comments

#115 Add two additional metrics labels cpu_model and initial_task_cpu.
  owca/kubernetes.py
  owca/mesos.py
  owca/platforms.py
  owca/runners/measurement.py
  tests/runners/test_runners_measurement.py
  tests/test_platforms.py
Labels: ready for review
