Repository intel/workload-collocation-agent, pull requests merged in 2019-02, with the labels that each got.

#37 Jenkinsfile: flake, unit tests, PEX files and Docker images
  Jenkinsfile
  workloads/tensorflow_inference/Dockerfile
  workloads/tensorflow_train/Dockerfile
Labels: ready for review

#38 [kubernetes:1] minimal DetectRunner scenario
  Pipfile
  Pipfile.lock
  configs/kubernetes_example.yaml
  owca/components.py
  owca/kubernetes_.py
  owca/platforms.py
  owca/runners/base.py
  setup.py
  workloads/stress_ng/stressng-deployment.yaml
Labels: request for comments

#40 Fix intendation, remove prints and add SetEffectiveRootUid for perf
  owca/perf.py
  owca/security.py
  tests/test_perf.py
Labels: ready for review

#23 Stress-ng as aurora task
  owca/wrapper/parser_stress_ng.py
  tests/wrapper/test_parser_stress_ng.py
  tox.ini
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
  workloads/stress_ng/Dockerfile
  workloads/stress_ng/stress_ng.aurora
Labels: ready for review

#41 allocations [1]: allocators and base allocations modules
  owca/allocations.py
  owca/allocators.py
  owca/testing.py
  tests/allocations/test_allocations_dict.py
  tests/allocations/test_allocations_numeric.py
  tests/test_runner.py
Labels: ready for review

#35 Trace decorator improvements
  owca/logger.py
Labels: ready for review, trivial

#43 allocations [2]: metrics package to send multiple metrics sets at once
  owca/storage.py
  tests/storage/test_metrics_package.py
Labels: ready for review, trivial

#45 Fixing broken Jenkins build
  Jenkinsfile
  tox.ini
  workloads/cassandra_stress/Dockerfile
  workloads/mutilate/Dockerfile
  workloads/rpc_perf/Dockerfile
  workloads/specjbb/Dockerfile
  workloads/stress_ng/Dockerfile
  workloads/tensorflow_benchmark/Dockerfile
  workloads/tensorflow_inference/Dockerfile
  workloads/tensorflow_train/Dockerfile
  workloads/ycsb/Dockerfile
Labels: ready for review

#48 We do not need the cron anymore
  Jenkinsfile
Labels: ready for review, trivial

#47 Usign AIPG Intel optimized TF
  workloads/tensorflow_benchmark/Dockerfile
Labels: ready for review

#52 Handle task's pid races, during cgroups.tasks and resctrl sync
  owca/resctrl.py
  tests/test_resctrl.py
Labels: ready for review

#51 Allocation[4]: resctrl & allocations
  owca/cbm_bits.py
  owca/resctrl.py
  owca/resctrl_allocations.py
  tests/cbm_bits/test_cbm.py
  tests/resctrl/test_resctrl_allocations.py
  tests/resctrl/test_resctrl_helpers.py
  tests/resctrl/test_resctrl_measurements.py
  tests/test_main.py
  tests/test_resctrl.py
Labels: ready for review

#56 Add information in log about possible reason of disability to print O…
  owca/platforms.py
Labels: ready for review

#55 $USER is not set inside a container
  workloads/common.aurora
Labels: ready for review, trivial
