Repository intel/workload-collocation-agent, pull requests merged in 2019-03, with the labels that each got.

#54 Allocation[5]: containers & platforms
  docs/allocation.rst
  owca/containers.py
  owca/platforms.py
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  tests/test_platforms.py
  tests/test_runner.py
Labels: ready for review

#58 Debugging Aurora metadata and Mesos labels
  workloads/common.aurora
Labels: ready for review, trivial

#60 Printing extra labels before adding them to the map
  workloads/common.aurora
Labels: ready for review, trivial

#63 Allows to add additional labels to all newly created workloads
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
Labels: ready for review

#66 Update dependencies to latest available versions as of 2019.3.11
  Pipfile
  Pipfile.lock
  setup.py
  tox.ini
Labels: trivial

#68 Minor formatting fixes
  workloads/README.rst
Labels: ready for review, trivial

#64 Fix log tracing formatting and tests for perf.
  owca/perf.py
  tests/test_perf.py
Labels: trivial

#69 Adding workload_instance label
  workloads/common.aurora
Labels: ready for review, trivial

#71 [CRITICAL] Added missing dependency (setuptools) after pex update to 1.6.3
  setup.py
Labels: trivial

#70 Replace tox with make and simplify depedency definition
  .travis.yml
  Jenkinsfile
  Makefile
  Pipfile
  Pipfile.lock
  owca/components.py
  owca/platforms.py
  setup.py
  tox.ini
Labels: ready for review, trivial

#72 Adding contending_workload_instance label to anomaly metrics
  owca/detectors.py
  owca/runner.py
  owca/testing.py
  tests/test_anomalies.py
  tests/test_runner.py
Labels: ready for review

#74 Update docs to use make instead of tox.
  NOTICE
  README.rst
  component-licenses/NOTICE
  docs/development.rst
  docs/install.rst
  docs/wrappers.rst
  workloads/README.rst
Labels: trivial

#73 Check metrics exists in list of metrics include labels submatch tooling.
  owca/testing.py
  tests/test_testing.py
Labels: ready for review

#76 Fix Docker build specjbb by Jenkins
  workloads/specjbb/Dockerfile
Labels: ready for review

#61 Allocation[6]: detection runner.
  owca/components.py
  owca/containers.py
  owca/detectors.py
  owca/main.py
  owca/nodes.py
  owca/platforms.py
  owca/profiling.py
  owca/resctrl.py
  owca/runner.py
  owca/runners/__init__.py
  owca/runners/detection.py
  owca/runners/measurement.py
  owca/testing.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/test_cgroups.py
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  tests/test_main.py
  tests/test_profiling.py
  tests/test_runner.py
Labels: ready for review

#81 Mesos API timeout option
  owca/mesos.py
Labels: trivial

#79 Call setuid if needed
  owca/security.py
Labels: trivial

#82 Makefile following conventions for dist/clean and check
  Jenkinsfile
  Makefile
Labels: trivial

#59 Kubernetes[2]: containers, add ContainerSet and needed changes to ContainerManager.
  docs/detection.rst
  owca/cgroups_allocations.py
  owca/components.py
  owca/containers.py
  owca/kubernetes.py
  owca/metrics.py
  owca/perf.py
  owca/runners/allocation.py
  owca/testing.py
  tests/runners/test_runners_detection.py
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  tests/test_kubernetes.py
  tests/test_metrics.py
Labels: ready for review

#83 Fix setting storage and JMX ports by using ansible env
  workloads/cassandra/cassandra.aurora
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
Labels: ready for review

#77 Workloads usage warning.
  workloads/README.rst
Labels: ready for review

#85 Improve Jenkinsfile
  Jenkinsfile
Labels: ready for review
