Repository intel/workload-collocation-agent, pull requests merged in 2019-09, with the labels that each got.

#247 Fix problem with MB RDT allocations granularity.
  tests/resctrl/test_resctrl_allocations.py
  tests/runners/test_runners_allocation_helpers.py
  wca/platforms.py
  wca/resctrl_allocations.py
  wca/runners/allocation.py
Labels: ready for review

#252 Minor fixes of coding style.
  example/http_storage.py
  tests/test_security.py
  wca/databases.py
  wca/perf.py
  wca/resctrl.py
  workloads/common.py
Labels: ready for review

#259 Delete wrong cipher
  wca/security.py
Labels: ready for review, security

#263 Delete unused code in "workload_job_iterator"
  workloads/filter_plugins/workload_job_iterator.py
Labels: ready for review, trivial

#264 Update pipfile
  Jenkinsfile
  Pipfile
  Pipfile.lock
Labels: ready for review, security

#268 Delete coverage.xml
  coverage.xml
Labels: done, trivial

#270 Kubernetes hosts update
  Jenkinsfile
  tests/e2e/demo_scenarios/common/inventory-kubernetes.yaml
  tests/e2e/demo_scenarios/common/wca_config_kubernetes.yaml
Labels: ready for review
