Repository intel/workload-collocation-agent, pull requests merged in 2019-06, with the labels that each got.

#151 Validate JSON files
  Pipfile.lock
  tests/test_containers.py
  wca/kubernetes.py
  wca/mesos.py
  wca/nodes.py
Labels: ready for review

#152 Fix bug: FileNotFoundError after raises while read measurements
  wca/cgroups.py
  wca/containers.py
  wca/resctrl.py
Labels: bug, ready for review

#153 Cleaning of project structure
  Jenkinsfile
  Makefile
  setup.py
  tests/__init__.py
  tests/allocations/test_allocations_dict.py
  tests/extra/test_static_node.py
  tests/resctrl/test_resctrl_allocations.py
  tests/resctrl/test_resctrl_helpers.py
  tests/resctrl/test_resctrl_measurements.py
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_allocation_helpers.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/storage/test_metrics_package.py
  tests/test_anomalies.py
  tests/test_cgroups.py
  tests/test_cgroups_allocations.py
  tests/test_containers.py
  tests/test_kubernetes.py
  tests/test_main.py
  tests/test_mesos.py
  tests/test_perf.py
  tests/test_platforms.py
  tests/test_profiling.py
  tests/test_testing.py
  tests/tester/configs/tester_config.yaml
  tests/tester/configs/tester_example.yaml
  tests/tester/test_tester.py
  tests/tester/tester.py
  tests/tester/tester_config.yaml
  tests/testing.py
  tests/wrapper/test_parser.py
  tests/wrapper/test_parser_cassandra_stress.py
  tests/wrapper/test_parser_mutilate.py
  tests/wrapper/test_parser_rpc_perf.py
  tests/wrapper/test_parser_specjbb.py
  tests/wrapper/test_parser_stress_ng.py
  tests/wrapper/test_parser_tensorflow_benchmark_prediction.py
  tests/wrapper/test_parser_tensorflow_benchmark_training.py
  tests/wrapper/test_parser_ycsb.py
  workloads/wrapper/README.rst
  workloads/wrapper/wrapper/__init__.py
  workloads/wrapper/wrapper/parser.py
  workloads/wrapper/wrapper/parser_cassandra_stress.py
  workloads/wrapper/wrapper/parser_example_workload.py
  workloads/wrapper/wrapper/parser_mutilate.py
  workloads/wrapper/wrapper/parser_rpc_perf.py
  workloads/wrapper/wrapper/parser_specjbb.py
  workloads/wrapper/wrapper/parser_stress_ng.py
  workloads/wrapper/wrapper/parser_tensorflow_benchmark_prediction.py
  workloads/wrapper/wrapper/parser_tensorflow_benchmark_training.py
  workloads/wrapper/wrapper/parser_ycsb.py
  workloads/wrapper/wrapper/wrapper_main.py
Labels: ready for review

#155 Catch exception when pid not exist when create Mesos task
  wca/mesos.py
Labels: bug, ready for review

#156 Workloads
  Jenkinsfile
  workloads/cassandra/cassandra.py
  workloads/cassandra_stress/cassandra_stress.py
  workloads/common.py
  workloads/mutilate/mutilate.py
  workloads/redis/redis.py
  workloads/rpc_perf/rpc_perf.py
  workloads/run_workloads.yaml
  workloads/run_workloads_inventory.template.yaml
  workloads/specjbb/specjbb.py
  workloads/stress_ng/stress_ng.py
  workloads/tensorflow_benchmark/Dockerfile
  workloads/tensorflow_benchmark/tensorflow-benchmark-prediction.py
  workloads/tensorflow_benchmark/tensorflow-benchmark-training.py
  workloads/tensorflow_inference/Dockerfile
  workloads/tensorflow_inference/README.rst
  workloads/tensorflow_inference/inference
  workloads/tensorflow_inference/load_nn_weights.py
  workloads/tensorflow_inference/prep_dataset_fruits.py
  workloads/tensorflow_inference/requirements.txt
  workloads/tensorflow_inference/tensorflow_inference.aurora
  workloads/tensorflow_train/Dockerfile
  workloads/tensorflow_train/README.rst
  workloads/tensorflow_train/prep_dataset.py
  workloads/tensorflow_train/requirements.txt
  workloads/tensorflow_train/tensorflow_train.aurora
  workloads/tensorflow_train/training
  workloads/twemcache/twemcache.py
  workloads/ycsb/ycsb.py
Labels: ready for review

#149 Improve security of communication with external components.
  configs/kubernetes/kubernetes_example_allocator.yaml
  configs/mesos/mesos_external_detector.yaml
  docs/ssl.rst
  tests/fixtures/headers.json
  tests/test_databases.py
  tests/test_kubernetes.py
  tests/test_mesos.py
  tests/test_security.py
  tests/testing.py
  wca/components.py
  wca/config.py
  wca/databases.py
  wca/kubernetes.py
  wca/mesos.py
  wca/security.py
  wca/testing.py
Labels: work in progress

#119 Daemonset for wca
  Dockerfile
  Jenkinsfile
  docs/kubernetes.rst
  example/manifest/configmap.yaml
  example/manifest/daemonset.yaml
  example/manifest/namespace.yaml
Labels: ready for review, request for comments

#157 SSL object quick fixes and docs
  README.rst
  docs/ssl.rst
  wca/config.py
  wca/databases.py
  wca/security.py
Labels: ready for review

#164 Perf counter scaling as metrics
  tests/test_perf.py
  wca/metrics.py
  wca/perf.py
Labels: ready for review

#165 Updating labels in container's tasks
  tests/test_metrics.py
  wca/mesos.py
  wca/runners/measurement.py
  wca/storage.py
Labels: ready for review

#162 Extending WCA docs and more documentation about examples and configuration
  README.rst
  SECURITY.md
  configs/README.rst
  configs/extending/hello_world.yaml
  configs/extending/measurement_http_storage.yaml
  configs/mesos/mesos_external_detector.yaml
  coverage.xml
  docs/extending.rst
  docs/install.rst
  example/README.rst
  example/hello_world_runner.py
  example/hello_world_runner_with_dateutil.py
  example/http_storage.py
Labels: ready for review

#166 Update dependecies to latest versions
  Pipfile
  Pipfile.lock
  tox.ini
Labels: ready for review

#168 Update install.rst to mention make and update devlopement guide
  docs/development.rst
  docs/install.rst
Labels: ready for review

#171 Update README.rst - fixes in getting started
  README.rst
Labels: ready for review

#172 Update README.rst - fixes in getting started (#171)
  README.rst
Labels: ready for review

#173 Use NOPAllocator instead of ExampleDetector
  configs/mesos/mesos_example_allocator.yaml
  docs/install.rst
Labels: ready for review

#175 Fix time wait/action delay
  tests/runners/test_runners_measurement.py
  wca/runners/measurement.py
Labels: ready for review

#176 Update install.rst
  docs/install.rst
Labels: ready for review

#177 Update mesos.rst
  docs/mesos.rst
Labels: ready for review

#178 allocation.rst and detection.rst update
  docs/allocation.rst
  docs/detection.rst
Labels: ready for review

#182 Change tensorflow_benchmark Dockerfile
  workloads/tensorflow_benchmark/Dockerfile
Labels: ready for review

#184 Change eval to json parse in wrapper
  workloads/cassandra_stress/cassandra_stress.aurora
  workloads/cassandra_stress/cassandra_stress.py
  workloads/mutilate/mutilate.aurora
  workloads/mutilate/mutilate.py
  workloads/rpc_perf/rpc_perf.aurora
  workloads/rpc_perf/rpc_perf.py
  workloads/run_workloads_inventory.template.yaml
  workloads/specjbb/specjbb.aurora
  workloads/specjbb/specjbb.py
  workloads/stress_ng/stress_ng.aurora
  workloads/stress_ng/stress_ng.py
  workloads/tensorflow_benchmark/tensorflow-benchmark-prediction.aurora
  workloads/tensorflow_benchmark/tensorflow-benchmark-prediction.py
  workloads/tensorflow_benchmark/tensorflow-benchmark-training.aurora
  workloads/tensorflow_benchmark/tensorflow-benchmark-training.py
  workloads/wrapper/wrapper/wrapper_main.py
  workloads/ycsb/ycsb.aurora
  workloads/ycsb/ycsb.py
Labels: ready for review

#186 Verify that configuration file has proper ACLs during initialization
  tests/test_main.py
  wca/main.py
Labels: ready for review

#192 Update pex version
  Pipfile
  Pipfile.lock
Labels: ready for review
