Repository intel/workload-collocation-agent, pull requests merged in 2020-02, with the labels that each got.

#392 One pod workload mysql-hammerdb
  Jenkinsfile
  examples/kubernetes/monitoring/fluentd/configurations/hammerdb.conf
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/build_workload.tcl
  examples/kubernetes/workloads/mysql-hammerdb/base/hammerdb.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/mysql-hammerdb.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/mysql.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/workload.tcl
  examples/kubernetes/workloads/mysql-hammerdb/big/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/big/resources.yaml
  examples/kubernetes/workloads/mysql-hammerdb/medium/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/medium/resources.yaml
  examples/kubernetes/workloads/mysql-hammerdb/small/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/small/resources.yaml
  examples/workloads/hammerdb/Dockerfile
Labels: ready for review

#393 Uncore metrics update
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  wca/metrics.py
  wca/perf_uncore.py
  wca/runners/measurement.py
Labels: request for comments

#397 Workaround for broken cpuacct.usage counter from multi container Pods
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/test_containers.py
  tests/testing.py
  wca/cgroups.py
  wca/containers.py
Labels: ready for review

#398 Remove services
  examples/kubernetes/workloads/memcached-mutilate/base/memcached-mutilate.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/mysql-hammerdb.yaml
  examples/kubernetes/workloads/redis-memtier/base/redis-memtier.yaml
Labels: work in progress

#395 Add copyrights headers
  Jenkinsfile
  Makefile
  NOTICE
  examples/__init__.py
  examples/hello_world_runner.py
  examples/hello_world_runner_with_dateutil.py
  examples/http_storage.py
  examples/kubernetes/monitoring/wca/daemonset.yaml
  examples/kubernetes/monitoring/wca/kustomization.yaml
  examples/workloads/filter_plugins/workload_job_iterator.py
  tests/config/test_config.yaml
  tests/config/test_config_env.yaml
  tests/config/test_config_unsafe.yaml
  tests/config/test_dataclasses.yaml
  tests/config/test_dataclasses_exceed_maximum.yaml
  tests/config/test_dataclasses_invalid.yaml
  tests/config/test_dataclasses_invalid_field.yaml
  tests/config/test_dataclasses_invalid_union.yaml
  tests/config/test_dataclasses_too_long_path.yaml
  tests/config/test_dataclasses_validation.yaml
  tests/config/test_dataclasses_validation_invalid_dict.yaml
  tests/config/test_dataclasses_validation_invalid_list.yaml
  tests/ssl/test_ssl.py
  tests/ssl/zookeeper/good_configuration.py
  tests/ssl/zookeeper/weak_client_cert.py
  tests/test_resctrl.py
  tests/test_runner.py
  tests/test_wss.py
  tests/tester/tester.py
  wca/pmembw.py
  wca/wss.py
Labels: ready for review

#400 Improve enabled "uncore" metrics descriptions.
  docs/metrics.csv
  docs/metrics.rst
  wca/metrics.py
Labels: ready for review

#399 Remove pipenv
  .gitignore
  .travis.yml
  Dockerfile
  Dockerfile.kafka
  Jenkinsfile
  Makefile
  Pipfile
  Pipfile.lock
  README.rst
  docs/development.rst
  requirements.txt
  setup.py
  tests/ssl/zookeeper/README.md
Labels: ready for review

#403 Update dependencies
  Jenkinsfile
  requirements.txt
Labels: trivial

#407 Remove bandit from requirements.txt
  Jenkinsfile
  Makefile
  requirements.txt
Labels: ready for review

#408 Replace lshw with dmidecode
  wca/platforms.py
Labels: ready for review

#409 Remove lshw form Dockerfile
  Dockerfile
Labels: ready for review

#410 Outdated dependencies check
  Makefile
  requirements.txt
Labels: ready for review

#411 Add dmidecode binary
  Dockerfile
Labels: trivial

#402 Run wca DaemonSet as high priority, to not be preempted by other PoDs
  examples/kubernetes/monitoring/wca/daemonset.yaml
  examples/kubernetes/monitoring/wca/kustomization.yaml
  examples/kubernetes/monitoring/wca/priority_class.yaml
Labels: trivial

#412 Bugfix to handle empty listformat and fix dmidecode
  .gitignore
  Dockerfile
  tests/test_platforms.py
  wca/platforms.py
Labels: trivial

#413 Fix missing value StaticAllocator and allocations docs (added types)
  docs/allocation.rst
  docs/api.rst
  wca/extra/static_allocator.py
Labels: trivial

#404 Specjbb stabilize
  examples/kubernetes/workloads/specjbb/fixed/resources.yaml
  examples/kubernetes/workloads/specjbb/hbir/resources.yaml
  examples/kubernetes/workloads/specjbb/kustomization.yaml
  examples/kubernetes/workloads/specjbb/preset-big-220/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-big-60/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-medium/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-small/resources.yaml
Labels: ready for review

#414 Delete comments from document WCA Architecture v1.7
  README.rst
  docs/[Outdated] WCA Architecture v1.7.pdf
Labels: ready for review

#405 Workload mysql-hammerdb stabilize
  examples/kubernetes/monitoring/fluentd/configurations/hammerdb.conf
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/my.cnf
  examples/kubernetes/workloads/mysql-hammerdb/base/mysql-hammerdb.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/workload.tcl
  examples/kubernetes/workloads/mysql-hammerdb/big/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/big/resources.yaml
  examples/kubernetes/workloads/mysql-hammerdb/medium/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/medium/resources.yaml
  examples/kubernetes/workloads/mysql-hammerdb/small/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/small/resources.yaml
  tests/e2e/test_wca_metrics.py
Labels: ready for review

#418 Set limit and requests resources for kubernetes one pod workloads (memchaed-mutilate and redis-memtier)
  examples/kubernetes/workloads/memcached-mutilate/big/resources.yaml
  examples/kubernetes/workloads/memcached-mutilate/medium/resources.yaml
  examples/kubernetes/workloads/memcached-mutilate/small/resources.yaml
  examples/kubernetes/workloads/redis-memtier/big/resources.yaml
  examples/kubernetes/workloads/redis-memtier/medium/resources.yaml
  examples/kubernetes/workloads/redis-memtier/small/resources.yaml
Labels: ready for review

#416 Dram speed
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  docs/metrics_sources.rst
  wca/metrics.py
  wca/platforms.py
  wca/runners/measurement.py
Labels: ready for review

#417 Remove docker images from Jenkins node after build and push
  Jenkinsfile
Labels: request for comments

#422 Ignore removing mon_group if it was already removed
  tests/resctrl/test_resctrl_measurements.py
  wca/resctrl.py
Labels: trivial

#423 Documentation fix and log improvement
  docs/metrics.csv
  docs/metrics.rst
  wca/metrics.py
  wca/perf_uncore.py
Labels: ready for review

#419 Set a longer range for apm_memtier_alive
  examples/kubernetes/workloads/redis-memtier/base/redis-memtier.yaml
  examples/workloads/memtier_benchmark/Dockerfile
Labels: ready for review
