Repository intel/workload-collocation-agent, pull requests merged in 2020-11, with the labels that each got.

#544 Redis wss scenarios
  examples/kubernetes/scripts/hmem_experiments/scenarios.py
Labels: trivial

#545 Remove PKI files from repo. Moved to e2e server.
  Jenkinsfile
  tests/e2e/nginx/CA.crt
  tests/e2e/nginx/CA.key
  tests/e2e/nginx/anotherCA.crt
  tests/e2e/nginx/anotherCA.key
  tests/e2e/nginx/attribute-expiration-date-issued-too-early/server.crt
  tests/e2e/nginx/attribute-expiration-date-issued-too-early/server.key
  tests/e2e/nginx/attribute-expiration-date-past/server.crt
  tests/e2e/nginx/attribute-expiration-date-past/server.key
  tests/e2e/nginx/attribute-purpose/server.crt
  tests/e2e/nginx/attribute-purpose/server.key
  tests/e2e/nginx/correct-cert/server.crt
  tests/e2e/nginx/correct-cert/server.key
  tests/e2e/nginx/flipped-bit/server.crt
  tests/e2e/nginx/flipped-bit/server.key
  tests/e2e/nginx/self-signed-cert/server.crt
  tests/e2e/nginx/self-signed-cert/server.key
  tests/e2e/nginx/server-key.pem
  tests/e2e/nginx/server.crt
  tests/e2e/nginx/signed-by-another-CA/server.crt
  tests/e2e/nginx/signed-by-another-CA/server.key
  tests/e2e/test_wca_nginx_ssl.py
Labels: ready for review

#540 Add new workload redis-memtier form latency measurement
  examples/kubernetes/monitoring/fluentd/configurations/memtier.conf
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/dram-pmem/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/dram/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/pmem/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/_coldstart/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/big-wss/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/big/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/medium-wss/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/medium/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/small-wss/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/_hmem/toptier/small/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/base/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/base/redis-memtier-latency.yaml
  examples/kubernetes/workloads/redis-memtier-latency/big-wss/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/big/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/medium-wss/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/medium/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/small-wss/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier-latency/small/kustomization.yaml
Labels: ready for review

#552 Unit test fixes for scheduler and annotator
  tests/admission_controller/test_app_data_provider.py
  tests/admission_controller/test_service.py
  tests/scheduler/algorithms/test_base.py
  tests/scheduler/data_providers/test_cluster_data_provider.py
  wca/scheduler/algorithms/base.py
Labels: ready for review

#550 Add tests for cAdvisor's perf
  Makefile
  tests/cadvisor/Jenkinsfile
  tests/cadvisor/perf.json
  tests/cadvisor/requirements.txt
  tests/cadvisor/test_cadvisor_perf.py
Labels: ready for review

#536 Patching toptier limit
  examples/kubernetes/scripts/analyzer/results.py
  examples/kubernetes/scripts/hmem_experiments/kernel_parameters.py
  examples/kubernetes/scripts/hmem_experiments/scenarios.py
  examples/kubernetes/scripts/hmem_experiments/workload_runner.py
Labels: work in progress

#555 Referenced bytes performance
  examples/kubernetes/monitoring/cadvisor/README.rst
Labels: ready for review

#549 Add pmbench workload with normal distribution
  examples/kubernetes/workloads/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/dram-pmem/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/dram/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/pmem/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/_coldstart/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/big-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/big/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/medium-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/medium/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/small-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/_hmem/toptier/small/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/base/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/base/pmbench.yaml
  examples/kubernetes/workloads/pmbench-normal/big-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/big/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/medium-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/medium/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/small-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench-normal/small/kustomization.yaml
Labels: ready for review

#557 Removing unused code from runner and analyzer
  examples/kubernetes/scripts/analyzer/connection.py
  examples/kubernetes/scripts/analyzer/model.py
  examples/kubernetes/scripts/analyzer/results.py
  examples/kubernetes/scripts/analyzer/runner_analyzer.py
  examples/kubernetes/scripts/analyzer/serializator.py
  examples/kubernetes/scripts/analyzer/view.py
  examples/kubernetes/scripts/hmem_experiments/main.py
  examples/kubernetes/scripts/hmem_experiments/runner.py
  examples/kubernetes/scripts/hmem_experiments/workload_runner.py
Labels: ready for review

#551 Experiment HMEM
  examples/kubernetes/scripts/analyzer/metrics.py
  examples/kubernetes/scripts/analyzer/model.py
  examples/kubernetes/scripts/analyzer/results.py
  examples/kubernetes/scripts/analyzer/runner_analyzer.py
  examples/kubernetes/scripts/analyzer/serializator.py
  examples/kubernetes/scripts/hmem_experiments/kernel_parameters.py
  examples/kubernetes/scripts/hmem_experiments/main.py
  examples/kubernetes/scripts/hmem_experiments/scenarios.py
  examples/kubernetes/workloads/pmbench/big/kustomization.yaml
Labels: ready for review
