Repository intel/workload-collocation-agent, pull requests merged in 2020-10, with the labels that each got.

#513 WSS improvements (optional fraction thresholds and small fix)
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  examples/kubernetes/monitoring/wca/wca-config.yaml
  tests/test_wss.py
  tests/tester/configs/tester_example.yaml
  wca/cgroups.py
  wca/containers.py
  wca/metrics.py
  wca/runners/measurement.py
  wca/wss.py
Labels: ready for review, trivial

#514 Improvement Kubernetes docs
  docs/kubernetes.rst
  examples/kubernetes/monitoring/wca/DEVEL.md
  examples/kubernetes/monitoring/wca/README.md
  examples/kubernetes/monitoring/wca/daemonset.yaml
Labels: ready for review

#517 Update rules with labels.
  examples/kubernetes/monitoring/prometheus/prometheus_rule.pmem.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
Labels: ready for review

#518 Update docs and manual testing.
  docs/score_algorithm.rst
Labels: work in progress

#520 Fix WSS measure per pod rather than container
  tests/test_wss.py
  wca/containers.py
  wca/wss.py
Labels: ready for review

#521 Add params to memtier workload for different random clients seed.
  examples/kubernetes/workloads/redis-memtier/base/redis-memtier.yaml
Labels: ready for review, trivial

#516 Modify dockerfile for cAdvisor to build from fork
  Jenkinsfile
  examples/kubernetes/monitoring/cadvisor/Dockerfile.cadvisor
  examples/kubernetes/monitoring/cadvisor/README.rst
Labels: ready for review

#523 After WSS changes updates in Score, Also updates for HMEM specific.
  docs/score_algorithm.rst
  examples/kubernetes/monitoring/prometheus/prometheus_rule.pmem.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
Labels: work in progress

#526 Update 2lm score dashboard.
  examples/kubernetes/monitoring/grafana/2lm_dashboards/2lm_score_dashboard.json
  examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
Labels: ready for review

#527 Miner fixes to score_algorithm docs.
  docs/score_algorithm.rst
Labels: trivial

#528 Update main README.rst to mention score algorithm for PMEM memory modules.
  README.rst
Labels: trivial

#531 Fix cadvisor build docker image
  examples/kubernetes/monitoring/cadvisor/Dockerfile.cadvisor
Labels: trivial

#530 Redis memtier affinity fix
  examples/kubernetes/workloads/redis-memtier/kustomization.yaml
Labels: trivial

#532 Redis configuration fix
  examples/kubernetes/workloads/redis-memtier/_hmem/pmem/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/_hmem/toptier/kustomization.yaml
Labels: trivial

#512 Score with cAdvisor metrics
  examples/kubernetes/monitoring/cadvisor/daemonset.yaml
  examples/kubernetes/monitoring/cadvisor/service_monitor.yaml
  examples/kubernetes/monitoring/kube-state-metrics/deployment.yaml
  examples/kubernetes/monitoring/prometheus/cadvisor.md
  examples/kubernetes/monitoring/prometheus/cadvisor_prometheus_rule.score.yaml
  examples/kubernetes/monitoring/prometheus/kustomization.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.pmem-cadvisor.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
Labels: ready for review

#533 New per task metrics based on sched debug.
  README.rst
  configs/extra/static_measurements.yaml
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  examples/kubernetes/monitoring/wca/wca-config.yaml
  tests/fixtures/proc-1-sched.txt
  tests/fixtures/proc-2-sched.txt
  tests/test_sched_stats.py
  wca/containers.py
  wca/metrics.py
  wca/runners/measurement.py
  wca/sched_stats.py
Labels: ready for review

#534 Fix sched debug stats - collect per thread basis
  wca/containers.py
Labels: trivial

#529 Adding more metrics to experiment results
  docs/api.rst
  examples/kubernetes/scripts/analyzer/metrics.py
  examples/kubernetes/scripts/analyzer/results.py
  examples/kubernetes/scripts/analyzer/runner_analyzer.py
  examples/kubernetes/scripts/analyzer/serializator.py
  examples/kubernetes/scripts/hmem_experiments/kernel_parameters.py
  examples/kubernetes/scripts/hmem_experiments/main.py
  examples/kubernetes/scripts/hmem_experiments/scenarios.py
  examples/kubernetes/scripts/hmem_experiments/workload_runner.py
Labels: ready for review

#525 Pmbench PMEM experiment scenario
  examples/kubernetes/monitoring/wca/wca-config.yaml
  examples/kubernetes/scripts/analyzer/metrics.py
  examples/kubernetes/scripts/analyzer/model.py
  examples/kubernetes/scripts/analyzer/results.py
  examples/kubernetes/scripts/analyzer/runner_analyzer.py
  examples/kubernetes/scripts/analyzer/serializator.py
  examples/kubernetes/scripts/hmem_experiments/main.py
  examples/kubernetes/scripts/hmem_experiments/scenarios.py
  examples/kubernetes/workloads/pmbench/big-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench/big/kustomization.yaml
  examples/kubernetes/workloads/pmbench/medium-wss/kustomization.yaml
  examples/kubernetes/workloads/pmbench/medium/kustomization.yaml
Labels: ready for review

#539 Setting kernel parameters
  examples/kubernetes/monitoring/wca/wca-config.yaml
  examples/kubernetes/scripts/hmem_experiments/kernel_parameters.py
  examples/kubernetes/scripts/hmem_experiments/main.py
Labels: ready for review

#541 Workloads remove nodeSeletctor to filter nodes with "goal: service"
  examples/kubernetes/workloads/README.md
  examples/kubernetes/workloads/memcached-mutilate/base/memcached-mutilate.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/mysql-hammerdb.yaml
  examples/kubernetes/workloads/pmbench/base/pmbench.yaml
  examples/kubernetes/workloads/redis-memtier/base/redis-memtier.yaml
  examples/kubernetes/workloads/specjbb/base/specjbb.yaml
  examples/kubernetes/workloads/stress/base/stress.yaml
  examples/kubernetes/workloads/sysbench-memory/base/sysbench-memory.yaml
Labels: trivial

#542 Fix generated docs and one typo.
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  util/docs.py
  wca/metrics.py
  wca/runners/allocation.py
Labels: trivial
