Repository intel/workload-collocation-agent, pull requests merged in 2020-07, with the labels that each got.

#474 Additional readme changes
  examples/kubernetes/monitoring/cadvisor/README.rst
Labels: ready for review

#475 E2E test for nginx ssl
  Jenkinsfile
  Makefile
  examples/kubernetes/wca-scheduler/wca-scheduler-server.conf
  tests/e2e/nginx/CA.crt
  tests/e2e/nginx/CA.key
  tests/e2e/nginx/anotherCA.crt
  tests/e2e/nginx/anotherCA.key
  tests/e2e/nginx/attribute-expiration-date-issued-too-early/server.crt
  tests/e2e/nginx/attribute-expiration-date-issued-too-early/server.key
  tests/e2e/nginx/attribute-expiration-date-past/server.crt
  tests/e2e/nginx/attribute-expiration-date-past/server.key
  tests/e2e/nginx/attribute-purpose/server.crt
  tests/e2e/nginx/attribute-purpose/server.key
  tests/e2e/nginx/correct-cert/server.crt
  tests/e2e/nginx/correct-cert/server.key
  tests/e2e/nginx/flipped-bit/server.crt
  tests/e2e/nginx/flipped-bit/server.key
  tests/e2e/nginx/self-signed-cert/server.crt
  tests/e2e/nginx/self-signed-cert/server.key
  tests/e2e/nginx/server-key.pem
  tests/e2e/nginx/server.crt
  tests/e2e/nginx/signed-by-another-CA/server.crt
  tests/e2e/nginx/signed-by-another-CA/server.key
  tests/e2e/nginx/test_wca_nginx_ssl.py
Labels: ready for review

#479 Fix memtier_benchmark Dockerfile. Set redis version to 5.0.8
  examples/workloads/memtier_benchmark/Dockerfile
Labels: bug, ready for review, trivial

#466 Remove NodePort Services. Communication trough service between kube-scheduler and wca-scheduler
  Jenkinsfile
  examples/kubernetes/monitoring/README.md
  examples/kubernetes/monitoring/grafana/service.yaml
  examples/kubernetes/monitoring/prometheus/service.yaml
  examples/kubernetes/monitoring/prometheus/service_account.yaml
  examples/kubernetes/wca-scheduler/README.rst
  examples/kubernetes/wca-scheduler/config.yaml
  examples/kubernetes/wca-scheduler/scheduler-policy.yaml
  examples/kubernetes/wca-scheduler/wca-scheduler-deployment.yaml
Labels: ready for review

#478 Cadvisor image build
  Dockerfile.cadvisor
  Jenkinsfile
Labels: ready for review

#483 Deploy cadvisor alongside wca
  Jenkinsfile
  examples/kubernetes/README.rst
  examples/kubernetes/monitoring/cadvisor/Dockerfile.cadvisor
  examples/kubernetes/monitoring/cadvisor/daemonset.yaml
  examples/kubernetes/monitoring/cadvisor/kustomization.yaml
  examples/kubernetes/monitoring/cadvisor/namespace.yaml
  examples/kubernetes/monitoring/cadvisor/service.yaml
  examples/kubernetes/monitoring/cadvisor/service_monitor.yaml
  examples/kubernetes/monitoring/cadvisor/serviceaccount.yaml
  examples/kubernetes/monitoring/kustomization.yaml
  examples/kubernetes/monitoring/namespaces.yaml
  examples/kubernetes/monitoring/wca/daemonset.yaml
Labels: ready for review

#484 Remove prometehus start form nginx ssl e2e tests
  Jenkinsfile
Labels: bug, ready for review

#482 Unify create tls secrets for wca-scheduler and admission-controller
  examples/kubernetes/admission-controller/README.rst
  examples/kubernetes/admission-controller/mutating-webhook.yaml
  examples/kubernetes/wca-scheduler/README.rst
Labels: request for comments

#488 Adopt fluentd to containerd logs
  examples/kubernetes/monitoring/fluentd/configurations/fluent.conf
  examples/kubernetes/monitoring/fluentd/daemonset.yaml
Labels: ready for review
