Repository intel/workload-collocation-agent, pull requests merged in 2020-06, with the labels that each got.

#456 Configs, prom rules
  examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
  examples/kubernetes/wca-scheduler/config.yaml
  examples/kubernetes/workloads/redis-memtier/base/redis-memtier.yaml
  examples/kubernetes/workloads/redis-memtier/big-wss/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/big/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/big/resources.yaml
  tests/fixtures/prometheus_app_profile.json
  tests/scheduler/algorithms/test_score.py
  tests/scheduler/data_providers/test_cluster_score_data_provider.py
  tests/scheduler/experiments/test_experiments.py
  tests/scheduler/simulator/data_provider.py
  wca/scheduler/algorithms/score.py
  wca/scheduler/data_providers/cluster_data_provider.py
Labels: ready for review

#458 Find score. Script to change moving window and virtual PMEM Prometheus rules.
  examples/kubernetes/monitoring/prometheus/prometheus_rule.pmem.yaml
  examples/kubernetes/scripts/generator_prometheus_rules.py
Labels: ready for review

#463 Minor changes after testing Score README related content.
  examples/kubernetes/monitoring/prometheus/2lm_score2_dashboard.json
  examples/kubernetes/monitoring/prometheus/2lm_score_dashboard.json
  examples/kubernetes/monitoring/prometheus/prometheus_rule.pmem.yaml
  examples/kubernetes/scripts/generator_prometheus_rules.py
Labels: ready for review

#464 Fix for missing mount in kubernetes examples
  examples/kubernetes/monitoring/wca/daemonset.yaml
Labels: ready for review

#467 Final demo fixes
  examples/kubernetes/monitoring/grafana/2lm_dashboards/2lm_cluster_general_dashboard.json
  examples/kubernetes/monitoring/grafana/2lm_dashboards/2lm_profiling_internal_dashboard.json
  examples/kubernetes/monitoring/grafana/2lm_dashboards/2lm_score_dashboard.json
  examples/kubernetes/scripts/nodes.json
  examples/kubernetes/scripts/runner.py
  examples/kubernetes/scripts/workloads.json
  examples/kubernetes/wca-scheduler/config.yaml
  examples/kubernetes/workloads/memcached-mutilate/big/kustomization.yaml
  examples/kubernetes/workloads/memcached-mutilate/big/resources.yaml
Labels: ready for review

#469 mTLS research
  examples/kubernetes/wca-scheduler/README.rst
Labels: ready for review, trivial

#468 2lm final demo script
  examples/kubernetes/scripts/2lm_final_demo.sh
Labels: ready for review

#470 Update score list image [e2e-skip]
  docs/score_sorted_list.png
Labels: ready for review

#461 Working set size - stabilization
  docs/metrics.csv
  docs/metrics.rst
  tests/test_wss.py
  wca/cgroups.py
  wca/containers.py
  wca/metrics.py
  wca/resctrl.py
  wca/runners/measurement.py
  wca/wss.py
Labels: ready for review

#471 Nginx configuration file permissions
  examples/kubernetes/wca-scheduler/kustomization.yaml
  examples/kubernetes/wca-scheduler/pod_monitor.yaml
  examples/kubernetes/wca-scheduler/wca-scheduler-deployment.yaml
  examples/kubernetes/wca-scheduler/wca-scheduler-server.conf
Labels: ready for review

#472 Add PRM and HMEM perf configs for cAdvisor.
  examples/kubernetes/monitoring/cadvisor/perf-hmem-cascadelake.json
  examples/kubernetes/monitoring/cadvisor/perf-prm-skylake.json
Labels: work in progress

#473 README for cAdvisor configs
  examples/kubernetes/monitoring/cadvisor/README.rst
Labels: ready for review
