Repository intel/workload-collocation-agent, pull requests merged in 2020-01, with the labels that each got.

#373 Make gather_hw_mm_topology automatically enabled
  wca/platforms.py
  wca/runners/measurement.py
Labels: ready for review

#375 Example configs fixes
  configs/mesos/mesos_external_detector.yaml
  docs/extending.rst
  docs/external_detector_example.rst
  examples/external_package.py
  wca/runners/detection.py
Labels: ready for review

#377 Fix missing tools lshw and ipmctl in wca image standalone and remove command to support devel images.
  Dockerfile
  examples/kubernetes/monitoring/wca/daemonset.yaml
Labels: ready for review, trivial

#380 Fix missing 'hostIP' in PodList when Pod is in Pending state.
  tests/fixtures/kubeapi_invalid_res_missing_host_ip.json
  tests/test_kubernetes.py
  wca/kubernetes.py
Labels: ready for review

#378 WCA use master image for monitoring deployment and enabled RDT (auto)
  Jenkinsfile
  examples/kubernetes/monitoring/wca/wca-config.yaml
  examples/kubernetes/workloads/redis-memtier/base/memtier.yaml
  examples/kubernetes/workloads/stress/base/stress.yaml
  tests/runners/test_runners_measurement.py
  wca/runners/measurement.py
Labels: ready for review

#379 Pmembw
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  tests/fixtures/bandwidth_ipmctl_dimm.txt
  tests/fixtures/bandwidth_ipmctl_region.txt
  tests/fixtures/ipmctl_dimm.txt
  tests/fixtures/ipmctl_region.txt
  tests/test_pmembw.py
  wca/metrics.py
  wca/pmembw.py
  wca/runners/measurement.py
Labels: ready for review

#384 Fix pmembw
  tests/test_pmembw.py
  wca/pmembw.py
Labels: ready for review

#386 App prometheus rules
  examples/kubernetes/monitoring/fluentd/configurations/memtier.conf
  examples/kubernetes/monitoring/fluentd/configurations/mutilate.conf
  examples/kubernetes/monitoring/fluentd/configurations/stress.conf
  examples/kubernetes/monitoring/fluentd/configurations/sysbench.conf
  examples/kubernetes/monitoring/prometheus/kustomization.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.16-compatibility-rules-new-to-old.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.app.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.wca.yaml
  tests/e2e/test_wca_metrics.py
Labels: work in progress

#385 Delete 'taskset -cpu' in Kubernetes workloads
  examples/kubernetes/workloads/memcached-mutilate/base/kustomization.yaml
  examples/kubernetes/workloads/memcached-mutilate/base/memcached.yaml
  examples/kubernetes/workloads/memcached-mutilate/base/mutilate.yaml
  examples/kubernetes/workloads/memcached-mutilate/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/base/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/base/memtier.yaml
  examples/kubernetes/workloads/redis-memtier/base/redis.yaml
  examples/kubernetes/workloads/redis-memtier/kustomization.yaml
  examples/kubernetes/workloads/stress/base/kustomization.yaml
  examples/kubernetes/workloads/stress/base/stress.yaml
  examples/kubernetes/workloads/stress/kustomization.yaml
  examples/kubernetes/workloads/stress/stream-big/kustomization.yaml
  examples/kubernetes/workloads/stress/stream-medium/kustomization.yaml
  examples/kubernetes/workloads/stress/stream-small/kustomization.yaml
  examples/kubernetes/workloads/sysbench-memory/base/kustomization.yaml
  examples/kubernetes/workloads/sysbench-memory/base/sysbench-memory.yaml
  examples/kubernetes/workloads/sysbench-memory/kustomization.yaml
Labels: ready for review

#364 Specjbb workload for Kubernetes
  Jenkinsfile
  examples/kubernetes/monitoring/fluentd/configurations/fluent.conf
  examples/kubernetes/monitoring/fluentd/configurations/specjbb.conf
  examples/kubernetes/monitoring/fluentd/kustomization.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.wca.yaml
  examples/kubernetes/workloads/kustomization.yaml
  examples/kubernetes/workloads/specjbb/base/controller.yaml
  examples/kubernetes/workloads/specjbb/base/group.yaml
  examples/kubernetes/workloads/specjbb/base/kustomization.yaml
  examples/kubernetes/workloads/specjbb/fixed/kustomization.yaml
  examples/kubernetes/workloads/specjbb/fixed/resources.yaml
  examples/kubernetes/workloads/specjbb/hbir/kustomization.yaml
  examples/kubernetes/workloads/specjbb/hbir/resources.yaml
  examples/kubernetes/workloads/specjbb/kustomization.yaml
  examples/kubernetes/workloads/specjbb/preset-big-220/kustomization.yaml
  examples/kubernetes/workloads/specjbb/preset-big-220/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-big-60/kustomization.yaml
  examples/kubernetes/workloads/specjbb/preset-big-60/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-medium/kustomization.yaml
  examples/kubernetes/workloads/specjbb/preset-medium/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-small/kustomization.yaml
  examples/kubernetes/workloads/specjbb/preset-small/resources.yaml
  examples/workloads/specjbb/Dockerfile
  tests/e2e/test_wca_metrics.py
Labels: ready for review, work in progress

#388 Fix Kubernetes workloads
  Jenkinsfile
  examples/kubernetes/monitoring/README.md
  examples/kubernetes/monitoring/wca/daemonset.yaml
  examples/kubernetes/monitoring/wca/service_monitor.yaml
  examples/kubernetes/monitoring/wca/wca-config.yaml
  examples/kubernetes/workloads/memcached-mutilate/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/base/memtier.yaml
  examples/kubernetes/workloads/redis-memtier/kustomization.yaml
  examples/kubernetes/workloads/specjbb/base/group.yaml
  examples/kubernetes/workloads/specjbb/base/kustomization.yaml
  examples/kubernetes/workloads/specjbb/fixed/kustomization.yaml
  examples/kubernetes/workloads/specjbb/fixed/resources.yaml
  examples/kubernetes/workloads/specjbb/hbir/kustomization.yaml
  examples/kubernetes/workloads/specjbb/hbir/resources.yaml
  examples/kubernetes/workloads/specjbb/kustomization.yaml
  examples/kubernetes/workloads/stress/kustomization.yaml
  examples/kubernetes/workloads/sysbench-memory/kustomization.yaml
Labels: ready for review

#389 Remove print from perf module
  wca/perf.py
Labels: trivial

#390 New metrics to count offcore requrests counters for deamnd DRD and RFO (and fix other event id and mask for other events)
  docs/metrics.csv
  docs/metrics.rst
  tests/test_perf.py
  wca/metrics.py
  wca/perf_const.py
Labels: trivial

#387 One-pod workloads
  Jenkinsfile
  examples/kubernetes/monitoring/fluentd/README.md
  examples/kubernetes/monitoring/fluentd/configurations/memtier.conf
  examples/kubernetes/monitoring/fluentd/configurations/mutilate.conf
  examples/kubernetes/monitoring/fluentd/configurations/specjbb.conf
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
  examples/kubernetes/workloads/memcached-mutilate/base/kustomization.yaml
  examples/kubernetes/workloads/memcached-mutilate/base/memcached-mutilate.yaml
  examples/kubernetes/workloads/memcached-mutilate/base/memcached.yaml
  examples/kubernetes/workloads/memcached-mutilate/base/resources.yaml
  examples/kubernetes/workloads/memcached-mutilate/big/kustomization.yaml
  examples/kubernetes/workloads/memcached-mutilate/big/resources.yaml
  examples/kubernetes/workloads/memcached-mutilate/medium/kustomization.yaml
  examples/kubernetes/workloads/memcached-mutilate/medium/resources.yaml
  examples/kubernetes/workloads/memcached-mutilate/small/kustomization.yaml
  examples/kubernetes/workloads/memcached-mutilate/small/resources.yaml
  examples/kubernetes/workloads/redis-memtier/base/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/base/redis-memtier.yaml
  examples/kubernetes/workloads/redis-memtier/base/redis.yaml
  examples/kubernetes/workloads/redis-memtier/big/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/big/resources.yaml
  examples/kubernetes/workloads/redis-memtier/medium/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/medium/resources.yaml
  examples/kubernetes/workloads/redis-memtier/small/kustomization.yaml
  examples/kubernetes/workloads/redis-memtier/small/resources.yaml
  examples/kubernetes/workloads/specjbb/base/controller.yaml
  examples/kubernetes/workloads/specjbb/base/kustomization.yaml
  examples/kubernetes/workloads/specjbb/base/specjbb.yaml
  examples/kubernetes/workloads/specjbb/fixed/resources.yaml
  examples/kubernetes/workloads/specjbb/hbir/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-big-220/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-big-60/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-medium/resources.yaml
  examples/kubernetes/workloads/specjbb/preset-small/resources.yaml
Labels: work in progress

#376 HammerDB workload for Kubernetes
  Jenkinsfile
  Makefile
  examples/kubernetes/monitoring/fluentd/configurations/fluent.conf
  examples/kubernetes/monitoring/fluentd/configurations/hammerdb.conf
  examples/kubernetes/monitoring/fluentd/kustomization.yaml
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
  examples/kubernetes/workloads/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/build_workload.tcl
  examples/kubernetes/workloads/mysql-hammerdb/base/hammerdb.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/mysql.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/workload.tcl
  examples/kubernetes/workloads/mysql-hammerdb/big/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/big/resources.yaml
  examples/kubernetes/workloads/mysql-hammerdb/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/medium/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/medium/resources.yaml
  examples/kubernetes/workloads/mysql-hammerdb/small/kustomization.yaml
  examples/kubernetes/workloads/mysql-hammerdb/small/resources.yaml
  examples/workloads/hammerdb/Dockerfile
  examples/workloads/mysql_tpm_gauge/Dockerfile
  examples/workloads/mysql_tpm_gauge/mysql_tpm_gauge.py
  examples/workloads/wrapper/wrapper/parser_mysql_tpm_gauge.py
  examples/workloads/wrapper/wrapper/wrapper_main.py
  tests/e2e/test_wca_metrics.py
  tests/wrapper/test_mysql_tpm_gauge.py
Labels: ready for review
