Repository intel/workload-collocation-agent, pull requests merged in 2020-04, with the labels that each got.

#435 Prometheus rules for score2 [wait for #426 to be merged]
  examples/kubernetes/monitoring/prometheus/2lm_score2_dashboard.json
  examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
Labels: ready for review

#436 Dram hit integration with score
  tests/scheduler/algorithms/test_score.py
  wca/scheduler/algorithms/score.py
Labels: ready for review

#440 Cache bandwidth calculation to save external calls
  wca/runners/measurement.py
Labels: trivial

#438 More than four uncore metrics per pmu type
  docs/metrics.csv
  docs/metrics.rst
  tests/test_perf.py
  wca/metrics.py
  wca/perf.py
  wca/perf_uncore.py
  wca/runners/measurement.py
Labels: ready for review

#439 Fix bug in calculating Score2 in prometheus rules.
  examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
  examples/kubernetes/wca-scheduler/config.yaml
Labels: ready for review

#444 Stabilize specjbb big
  examples/kubernetes/workloads/specjbb/preset-big-60/kustomization.yaml
Labels: trivial

#442 Parsing data from zoneinfo
  configs/extra/static_measurements_directory.yaml
  docs/api.rst
  docs/metrics.csv
  docs/metrics.rst
  pytest.ini
  tests/fixtures/proc-zoneinfo.txt
  tests/runners/test_runners_allocation.py
  tests/runners/test_runners_detection.py
  tests/runners/test_runners_measurement.py
  tests/scheduler/simulator/reporting.py
  tests/test_zoneinfo.py
  tests/testing.py
  wca/metrics.py
  wca/runners/measurement.py
  wca/zoneinfo.py
Labels: ready for review

#447 Remove duplicate in rules
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
Labels: trivial

#452 Change imagePullPolicy in all workloads to Always
  examples/kubernetes/workloads/memcached-mutilate/base/memcached-mutilate.yaml
  examples/kubernetes/workloads/mysql-hammerdb/base/mysql-hammerdb.yaml
  examples/kubernetes/workloads/redis-memtier/base/redis-memtier.yaml
  examples/kubernetes/workloads/redis-memtier/big-wss/resources.yaml
  examples/kubernetes/workloads/redis-memtier/big/resources.yaml
  examples/kubernetes/workloads/redis-memtier/medium/resources.yaml
  examples/kubernetes/workloads/specjbb/base/specjbb.yaml
  examples/kubernetes/workloads/stress/base/stress.yaml
  examples/kubernetes/workloads/sysbench-memory/base/sysbench-memory.yaml
  examples/kubernetes/workloads/sysbench-memory/medium/resources.yaml
Labels: ready for review, trivial

#450 Change prometheus metric apm_hammerdb_ops
  examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
Labels: ready for review, trivial

#451 Mutating webhook
  examples/kubernetes/admission-controller/Dockerfile
  examples/kubernetes/admission-controller/README.rst
  examples/kubernetes/admission-controller/keys/cert_sign_request.yaml
  examples/kubernetes/admission-controller/keys/csr.conf
  examples/kubernetes/admission-controller/mutating-webhook.yaml
  examples/kubernetes/admission-controller/webhook-deployment.yaml
  examples/kubernetes/admission-controller/webhook-svc.yaml
  wca/admission-controller/service.py
Labels: ready for review

#448 Limiting cpu for experiments
  examples/kubernetes/wca-scheduler/config.yaml
  tests/scheduler/simulator/data_provider.py
  wca/scheduler/algorithms/fit.py
  wca/scheduler/algorithms/score.py
  wca/scheduler/data_providers/__init__.py
  wca/scheduler/data_providers/cluster_data_provider.py
Labels: ready for review
